name: bsdtar

on: [pull_request, workflow_dispatch]

jobs:
  alpine-musl:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      version: 3.19.1

  windows-mingw:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-windows.yml
    with:
      workflow: ${{ github.workflow }}
      version: 2022

  test-alpine:
    needs: alpine-musl
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/test-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  test-ubuntu:
    needs: alpine-musl
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  test-windows:
    needs: windows-mingw
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/test-windows.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-mingw

  test-nanoserver:
    needs: windows-mingw
    uses: ./.github/workflows/test-nanoserver.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-mingw

  release:
    needs: [test-alpine,
            test-ubuntu,
            test-windows,
            test-nanoserver]
    uses: ./.github/workflows/release.yml
    with:
      workflow: ${{ github.workflow }}
      tool_version: '3.7.5'
      prepare_body: |
        bsdtar -Oxf ./build-musl/build-musl.tar.gz build-musl.md >> body.md
        bsdtar -Oxf ./build-mingw/build-mingw.tar.gz build-mingw.md >> body.md
      artifacts: ./build-musl/build-musl.tar.gz,./build-mingw/build-mingw.tar.gz
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
